//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Notepad.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Notepad.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 请输入邮箱账号 的本地化字符串。
        /// </summary>
        internal static string AccountInput_PlaceholderText {
            get {
                return ResourceManager.GetString("AccountInput.PlaceholderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 账号 的本地化字符串。
        /// </summary>
        internal static string AccountInput_PrefixText {
            get {
                return ResourceManager.GetString("AccountInput.PrefixText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 自动登录 的本地化字符串。
        /// </summary>
        internal static string AutoLoginLabel_Text {
            get {
                return ResourceManager.GetString("AutoLoginLabel.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 关闭 的本地化字符串。
        /// </summary>
        internal static string Button_Close {
            get {
                return ResourceManager.GetString("Button.Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 保存 的本地化字符串。
        /// </summary>
        internal static string Button_Save {
            get {
                return ResourceManager.GetString("Button.Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 复制失败 的本地化字符串。
        /// </summary>
        internal static string CopyFailed {
            get {
                return ResourceManager.GetString("CopyFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 复制成功 的本地化字符串。
        /// </summary>
        internal static string CopySuccess {
            get {
                return ResourceManager.GetString("CopySuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请输入密钥 的本地化字符串。
        /// </summary>
        internal static string Decrypt {
            get {
                return ResourceManager.GetString("Decrypt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 密钥不正确 的本地化字符串。
        /// </summary>
        internal static string Decrypt_KeyIncorrect {
            get {
                return ResourceManager.GetString("Decrypt_KeyIncorrect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 什么都没有…… 的本地化字符串。
        /// </summary>
        internal static string DEFAULT_NoData {
            get {
                return ResourceManager.GetString("DEFAULT_NoData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 确认删除{0}条笔记，删除后不可恢复 的本地化字符串。
        /// </summary>
        internal static string FloatButton_ConfigBtn_Delete_Notification_Content {
            get {
                return ResourceManager.GetString("FloatButton.ConfigBtn.Delete.Notification.Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 确认删除 的本地化字符串。
        /// </summary>
        internal static string FloatButton_ConfigBtn_Delete_Notification_Title {
            get {
                return ResourceManager.GetString("FloatButton.ConfigBtn.Delete.Notification.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 全选 的本地化字符串。
        /// </summary>
        internal static string FloatButton_ConfigBtn_Select_All {
            get {
                return ResourceManager.GetString("FloatButton.ConfigBtn.Select.All", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 取消 的本地化字符串。
        /// </summary>
        internal static string FloatButton_ConfigBtn_Select_Cancel {
            get {
                return ResourceManager.GetString("FloatButton.ConfigBtn.Select.Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap icon {
            get {
                object obj = ResourceManager.GetObject("icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似 语言 的本地化字符串。
        /// </summary>
        internal static string Lang {
            get {
                return ResourceManager.GetString("Lang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 跟随系统,中文,英文 的本地化字符串。
        /// </summary>
        internal static string LangSelect_Items {
            get {
                return ResourceManager.GetString("LangSelect.Items", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 删除失败： 的本地化字符串。
        /// </summary>
        internal static string Loading_DeleteFailed {
            get {
                return ResourceManager.GetString("Loading_DeleteFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 删除成功 的本地化字符串。
        /// </summary>
        internal static string Loading_DeleteSuccess {
            get {
                return ResourceManager.GetString("Loading_DeleteSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 不支持该邮箱 的本地化字符串。
        /// </summary>
        internal static string Loading_EMallNotSupport {
            get {
                return ResourceManager.GetString("Loading_EMallNotSupport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 加载中…… 的本地化字符串。
        /// </summary>
        internal static string Loading_Loading {
            get {
                return ResourceManager.GetString("Loading_Loading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 加载配置中…… 的本地化字符串。
        /// </summary>
        internal static string Loading_LoadingSettings {
            get {
                return ResourceManager.GetString("Loading_LoadingSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 努力加载数据中…… 的本地化字符串。
        /// </summary>
        internal static string Loading_LoadNotes {
            get {
                return ResourceManager.GetString("Loading_LoadNotes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 登录失败： 的本地化字符串。
        /// </summary>
        internal static string Loading_LoginFailed {
            get {
                return ResourceManager.GetString("Loading_LoginFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 注册{0}失败 的本地化字符串。
        /// </summary>
        internal static string Loading_RegisterHotKeyFailed {
            get {
                return ResourceManager.GetString("Loading_RegisterHotKeyFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 保存失败： 的本地化字符串。
        /// </summary>
        internal static string Loading_SaveFailed {
            get {
                return ResourceManager.GetString("Loading_SaveFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 保存成功 的本地化字符串。
        /// </summary>
        internal static string Loading_SaveSuccess {
            get {
                return ResourceManager.GetString("Loading_SaveSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 已锁定，请在{0}秒后重试 的本地化字符串。
        /// </summary>
        internal static string Lock_CountDown {
            get {
                return ResourceManager.GetString("Lock_CountDown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 登录 的本地化字符串。
        /// </summary>
        internal static string LoginButton_Text {
            get {
                return ResourceManager.GetString("LoginButton.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0}秒后自动登录，取消 的本地化字符串。
        /// </summary>
        internal static string LoginButton_Text_AutoLogin {
            get {
                return ResourceManager.GetString("LoginButton.Text.AutoLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 加载中…… 的本地化字符串。
        /// </summary>
        internal static string LoginButton_Text_Loding {
            get {
                return ResourceManager.GetString("LoginButton.Text.Loding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 登录中 的本地化字符串。
        /// </summary>
        internal static string LoginButton_Text_Logging {
            get {
                return ResourceManager.GetString("LoginButton.Text.Logging", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 授权失败 的本地化字符串。
        /// </summary>
        internal static string Mall_AuthFailed {
            get {
                return ResourceManager.GetString("Mall_AuthFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 授权失败密码不正确 的本地化字符串。
        /// </summary>
        internal static string Mall_AuthFailed_IncorrectPassword {
            get {
                return ResourceManager.GetString("Mall_AuthFailed_IncorrectPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 连接服务器失败 的本地化字符串。
        /// </summary>
        internal static string Mall_ConnectFailed {
            get {
                return ResourceManager.GetString("Mall_ConnectFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 程序崩溃了 的本地化字符串。
        /// </summary>
        internal static string Notification_AppCrash {
            get {
                return ResourceManager.GetString("Notification_AppCrash", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 确认 的本地化字符串。
        /// </summary>
        internal static string Notification_Confirm {
            get {
                return ResourceManager.GetString("Notification_Confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 重新加载 的本地化字符串。
        /// </summary>
        internal static string Notification_LoadNotes_Reload {
            get {
                return ResourceManager.GetString("Notification_LoadNotes_Reload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 加载数据失败 的本地化字符串。
        /// </summary>
        internal static string Notification_LoadNotes_Title_Failed {
            get {
                return ResourceManager.GetString("Notification_LoadNotes_Title_Failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 退出 的本地化字符串。
        /// </summary>
        internal static string NotifyIcon_Exit {
            get {
                return ResourceManager.GetString("NotifyIcon_Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 锁定 的本地化字符串。
        /// </summary>
        internal static string NotifyIcon_Lock {
            get {
                return ResourceManager.GetString("NotifyIcon_Lock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 打开笔记 的本地化字符串。
        /// </summary>
        internal static string NotifyIcon_Open {
            get {
                return ResourceManager.GetString("NotifyIcon_Open", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 密码 的本地化字符串。
        /// </summary>
        internal static string PasswordInput_PrefixText {
            get {
                return ResourceManager.GetString("PasswordInput.PrefixText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 PIN 的本地化字符串。
        /// </summary>
        internal static string PIN {
            get {
                return ResourceManager.GetString("PIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 确认PIN 的本地化字符串。
        /// </summary>
        internal static string PIN_Confirm {
            get {
                return ResourceManager.GetString("PIN_Confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 PIN不一致 的本地化字符串。
        /// </summary>
        internal static string PIN_Difference {
            get {
                return ResourceManager.GetString("PIN_Difference", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 PIN不正确 的本地化字符串。
        /// </summary>
        internal static string PIN_Incorrect {
            get {
                return ResourceManager.GetString("PIN_Incorrect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 新PIN 的本地化字符串。
        /// </summary>
        internal static string PIN_New {
            get {
                return ResourceManager.GetString("PIN_New", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 设置PIN 的本地化字符串。
        /// </summary>
        internal static string PIN_Setting {
            get {
                return ResourceManager.GetString("PIN_Setting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 记住密码 的本地化字符串。
        /// </summary>
        internal static string RememberLabel_Text {
            get {
                return ResourceManager.GetString("RememberLabel.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 设置 的本地化字符串。
        /// </summary>
        internal static string Setting {
            get {
                return ResourceManager.GetString("Setting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 加密数据 的本地化字符串。
        /// </summary>
        internal static string Setting_EncryptData {
            get {
                return ResourceManager.GetString("Setting_EncryptData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 加密密钥 的本地化字符串。
        /// </summary>
        internal static string Setting_EncryptKey {
            get {
                return ResourceManager.GetString("Setting_EncryptKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 锁快捷键 的本地化字符串。
        /// </summary>
        internal static string Setting_LockHotKey {
            get {
                return ResourceManager.GetString("Setting_LockHotKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 关闭时最小化至托盘 的本地化字符串。
        /// </summary>
        internal static string Setting_Min {
            get {
                return ResourceManager.GetString("Setting_Min", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 面板快捷键 的本地化字符串。
        /// </summary>
        internal static string Setting_OpenHotKey {
            get {
                return ResourceManager.GetString("Setting_OpenHotKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 超时时间 的本地化字符串。
        /// </summary>
        internal static string Setting_PINTimeout {
            get {
                return ResourceManager.GetString("Setting_PINTimeout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 分钟 的本地化字符串。
        /// </summary>
        internal static string Setting_PINTimeoutMinute {
            get {
                return ResourceManager.GetString("Setting_PINTimeoutMinute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 主色调 的本地化字符串。
        /// </summary>
        internal static string Setting_PrimaryColor {
            get {
                return ResourceManager.GetString("Setting_PrimaryColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 重置 的本地化字符串。
        /// </summary>
        internal static string Setting_PrimaryColorReset {
            get {
                return ResourceManager.GetString("Setting_PrimaryColorReset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 开机自启动 的本地化字符串。
        /// </summary>
        internal static string Setting_Startup {
            get {
                return ResourceManager.GetString("Setting_Startup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 时间降序,时间升序,名称升序,名称降序 的本地化字符串。
        /// </summary>
        internal static string SortButton_Tips {
            get {
                return ResourceManager.GetString("SortButton.Tips", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &lt;svg viewBox=&quot;0 0 1024 1024&quot; version=&quot;1.1&quot; xmlns=&quot;http://www.w3.org/2000/svg&quot;&gt;&lt;path d=&quot;M740.828151 485.179145 538.820344 485.179145 538.820344 283.185664c0-14.81645-11.989055-26.820855-26.820855-26.820855-14.769378 0-26.790156 12.004405-26.790156 26.820855l-0.013303 201.99348L283.200502 485.179145c-14.801101 0-26.820855 12.019755-26.820855 26.820855 0 14.81645 12.019755 26.819832 26.820855 26.819832l201.991434 0-0.013303 201.994504c0 14.800078 12.051477 26.821879 26.820855 26.821879 14.8318 0 26.820855-12.0 [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string Svg_Add {
            get {
                return ResourceManager.GetString("Svg_Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &lt;svg viewBox=&quot;0 0 1024 1024&quot; version=&quot;1.1&quot; xmlns=&quot;http://www.w3.org/2000/svg&quot;&gt;&lt;path d=&quot;M871 298.1h-75.4v477.8c0 55.5-45 100.6-100.6 100.6H368.1c-55.6 0-100.6-45-100.6-100.6V298.1h-50.3c-13.9 0-25.1-11.3-25.1-25.1 0-13.9 11.3-25.1 25.1-25.1H871c13.9 0 25.1 11.3 25.1 25.1 0.1 13.8-11.2 25.1-25.1 25.1z m-125.7 0H317.8v477.8c0 27.8 22.5 50.3 50.3 50.3H695c27.8 0 50.3-22.5 50.3-50.3V298.1zM594.4 700.4c-13.9 0-25.1-11.3-25.1-25.1V398.6c0-13.9 11.3-25.1 25.1-25.1 13.9 0 25.1 11.3 25.1 25.1v276.6c0 14-11.2 25.2-25. [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string Svg_Delete {
            get {
                return ResourceManager.GetString("Svg_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &lt;svg viewBox=&quot;64 64 896 896&quot;&gt;&lt;path d=&quot;M799.86 166.31c.02 0 .04.02.08.06l57.69 57.7c.04.03.05.05.06.08a.12.12 0 010 .06c0 .03-.02.05-.06.09L569.93 512l287.7 287.7c.04.04.05.06.06.09a.12.12 0 010 .07c0 .02-.02.04-.06.08l-57.7 57.69c-.03.04-.05.05-.07.06a.12.12 0 01-.07 0c-.03 0-.05-.02-.09-.06L512 569.93l-287.7 287.7c-.04.04-.06.05-.09.06a.12.12 0 01-.07 0c-.02 0-.04-.02-.08-.06l-57.69-57.7c-.04-.03-.05-.05-.06-.07a.12.12 0 010-.07c0-.03.02-.05.06-.09L454.07 512l-287.7-287.7c-.04-.04-.05-.06-.06-.09a.12.12 0  [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string Svg_DialogClose {
            get {
                return ResourceManager.GetString("Svg_DialogClose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &lt;svg viewBox=&quot;0 0 1024 1024&quot; version=&quot;1.1&quot; xmlns=&quot;http://www.w3.org/2000/svg&quot;&gt;&lt;path d=&quot;M491.217455 754.641455 11.147636 274.571636c-11.031273-10.938182-11.031273-28.928 0-39.982545 11.054545-11.008 29.021091-11.008 40.005818 0L512 695.458909l460.869818-460.846545c11.031273-11.008 28.928-11.008 40.005818 0 11.031273 11.054545 11.031273 29.044364 0 39.982545L532.829091 754.641455c-5.701818 5.725091-13.312 8.308364-20.829091 8.098909C504.482909 762.949818 496.919273 760.366545 491.217455 754.641455&quot;&gt;&lt;/path&gt;&lt;/s [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string Svg_Down {
            get {
                return ResourceManager.GetString("Svg_Down", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &lt;svg viewBox=&quot;0 0 1024 1024&quot; version=&quot;1.1&quot; xmlns=&quot;http://www.w3.org/2000/svg&quot;&gt;&lt;path d=&quot;M153.6 902.656a32.256 32.256 0 0 1 0-64h716.8a32.256 32.256 0 0 1 0 64zM743.936 151.04l72.192 72.192a51.2 51.2 0 0 1 0 72.192L358.4 751.616a51.2 51.2 0 0 1-36.352 14.848H226.816a25.6 25.6 0 0 1-25.6-25.6v-97.792a51.2 51.2 0 0 1 14.848-36.352l455.68-455.68a51.2 51.2 0 0 1 72.192 0z m-478.72 497.152v54.272h54.272l442.88-442.88L708.096 204.8z&quot;&gt;&lt;/path&gt;&lt;/svg&gt; 的本地化字符串。
        /// </summary>
        internal static string Svg_Edit {
            get {
                return ResourceManager.GetString("Svg_Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &lt;svg viewBox=&quot;0 0 1024 1024&quot; version=&quot;1.1&quot; xmlns=&quot;http://www.w3.org/2000/svg&quot;&gt;&lt;path d=&quot;M139.5 554.72h646.81L566.66 774.38c-16.2 16.2-16.2 42.47 0 58.68 16.21 16.21 42.48 16.21 58.69 0l290.49-290.49c16.2-16.2 16.2-42.48 0-58.68l-290.49-290.5c-8.1-8.11-18.72-12.16-29.35-12.16-10.62 0-21.24 4.05-29.34 12.16-16.2 16.2-16.2 42.48 0 58.68l219.65 219.65H139.5c-22.92 0-41.5 18.58-41.5 41.5s18.59 41.5 41.5 41.5z&quot;&gt;&lt;/path&gt;&lt;/svg&gt; 的本地化字符串。
        /// </summary>
        internal static string Svg_Exit {
            get {
                return ResourceManager.GetString("Svg_Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &lt;svg viewBox=&quot;0 0 1024 1024&quot; version=&quot;1.1&quot; xmlns=&quot;http://www.w3.org/2000/svg&quot;&gt;&lt;path d=&quot;M774.016 85.333333h-112.426667V21.76a21.333333 21.333333 0 0 0-42.666666 0V85.333333h-85.333334V21.76a21.333333 21.333333 0 0 0-42.666666 0V85.333333h-85.333334V21.76a21.333333 21.333333 0 0 0-42.666666 0V85.333333H250.496a122.368 122.368 0 0 0-122.24 122.24v694.186667A122.368 122.368 0 0 0 250.496 1024h523.52a122.368 122.368 0 0 0 122.24-122.24V207.573333A122.368 122.368 0 0 0 774.016 85.333333z m79.573333 816.426667A79. [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string Svg_Icon {
            get {
                return ResourceManager.GetString("Svg_Icon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &lt;svg viewBox=&quot;0 0 1024 1024&quot; version=&quot;1.1&quot; xmlns=&quot;http://www.w3.org/2000/svg&quot;&gt;&lt;path d=&quot;M512 430.08a81.92 81.92 0 1 1-81.92 81.92 81.92 81.92 0 0 1 81.92-81.92z m327.68 40.96a40.96 40.96 0 1 1-40.96 40.96 40.96 40.96 0 0 1 40.96-40.96zM184.32 471.04a40.96 40.96 0 1 1-40.96 40.96 40.96 40.96 0 0 1 40.96-40.96z&quot;&gt;&lt;/path&gt;&lt;/svg&gt; 的本地化字符串。
        /// </summary>
        internal static string Svg_Lite {
            get {
                return ResourceManager.GetString("Svg_Lite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &lt;svg viewBox=&quot;0 0 1024 1024&quot; version=&quot;1.1&quot; xmlns=&quot;http://www.w3.org/2000/svg&quot;&gt;&lt;path d=&quot;M880.91005631 90.125H332.55160842a52.70143661 52.70143661 0 0 0-52.70143661 52.70143661v105.40287324H143.08994369a52.70143661 52.70143661 0 0 0-52.70143661 52.70143661v579.71580276a52.70143661 52.70143661 0 0 0 52.70143661 52.70143662h579.71580277a52.70143661 52.70143661 0 0 0 52.70143662-52.70143662v-137.55074935h105.40287323a52.70143661 52.70143661 0 0 0 52.70143661-52.70143662V142.82643661a52.70143661 52.70143661 0 0 0 [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string Svg_Max {
            get {
                return ResourceManager.GetString("Svg_Max", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &lt;svg viewBox=&quot;0 0 1024 1024&quot; version=&quot;1.1&quot; xmlns=&quot;http://www.w3.org/2000/svg&quot;&gt;&lt;path d=&quot;M399.36 563.2c-7.68 0-12.8-2.56-17.92-7.68l-112.64-112.64c-7.68-10.24-12.8-20.48-12.8-33.28s5.12-23.04 12.8-33.28l112.64-112.64c10.24-10.24 25.6-10.24 35.84 0 10.24 10.24 10.24 25.6 0 35.84L309.76 409.6l110.08 110.08c10.24 10.24 10.24 25.6 0 35.84-5.12 5.12-12.8 7.68-20.48 7.68z m-94.72-148.48zM568.32 768h-204.8c-15.36 0-25.6-10.24-25.6-25.6s10.24-25.6 25.6-25.6h204.8c81.92 0 148.48-64 148.48-140.8S650.24 435.2 568.32 435 [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string Svg_Restore {
            get {
                return ResourceManager.GetString("Svg_Restore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &lt;svg viewBox=&quot;0 0 1024 1024&quot; version=&quot;1.1&quot; xmlns=&quot;http://www.w3.org/2000/svg&quot;&gt;&lt;path d=&quot;M502.184585 951.221073c-12.487805 0-24.97561 0-37.463414-2.497561-37.463415-2.497561-64.936585-32.468293-64.936586-67.434146 0-24.97561-14.985366-44.956098-37.463414-54.946342-24.97561-9.990244-52.44878-4.995122-69.931708 12.487805l-22.478048 14.985366c-24.97561 9.990244-52.44878 4.995122-72.429269-9.990244-17.482927-14.985366-37.463415-32.468293-52.44878-49.951219-24.97561-27.473171-22.478049-67.434146 4.995122-92.409756 [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string Svg_Setting {
            get {
                return ResourceManager.GetString("Svg_Setting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &lt;svg viewBox=&quot;0 0 1024 1024&quot; version=&quot;1.1&quot; xmlns=&quot;http://www.w3.org/2000/svg&quot;&gt;&lt;path d=&quot;M406.72323609 154.94049073c4.40991211 0 8.05352783 3.64361573 8.05352782 8.05352783V406.53125c0 4.41073609-3.64361573 8.0543518-8.05352782 8.0543518H162.99401856c-4.40991211 0-8.05352783-3.64361573-8.05352783-8.0543518V162.99401856c0-4.40991211 3.64361573-8.05352783 8.05352782-8.05352783h243.72921754m0-64.81549073H162.99401856C122.91589355 90.125 90.125 122.91589355 90.125 162.99401856V406.53125c0 40.27011109 32.79089356  [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string Svg_ShowCard {
            get {
                return ResourceManager.GetString("Svg_ShowCard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &lt;svg viewBox=&quot;0 0 1024 1024&quot; version=&quot;1.1&quot; xmlns=&quot;http://www.w3.org/2000/svg&quot;&gt;&lt;path d=&quot;M170.666667 213.333333h682.666666v85.333334H170.666667V213.333333z m0 512h426.666666v85.333334H170.666667v-85.333334z m0-256h682.666666v85.333334H170.666667v-85.333334z&quot;&gt;&lt;/path&gt;&lt;/svg&gt; 的本地化字符串。
        /// </summary>
        internal static string Svg_ShowList {
            get {
                return ResourceManager.GetString("Svg_ShowList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &lt;svg viewBox=&quot;0 0 1024 1024&quot; version=&quot;1.1&quot; xmlns=&quot;http://www.w3.org/2000/svg&quot;&gt;&lt;path d=&quot;M491.217455 232.401455 11.147636 712.448c-11.031273 10.914909-11.031273 28.904727 0 39.959273 11.054545 11.031273 29.021091 11.031273 40.005818 0L512 291.560727 972.869818 752.407273c11.031273 11.031273 28.928 11.031273 40.005818 0 11.031273-11.054545 11.031273-29.044364 0-39.959273L532.829091 232.401455C527.127273 226.653091 519.517091 224.046545 512 224.279273 504.482909 224.046545 496.919273 226.653091 491.217455 232.4 [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string Svg_Up {
            get {
                return ResourceManager.GetString("Svg_Up", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 修改 的本地化字符串。
        /// </summary>
        internal static string Text_Edit {
            get {
                return ResourceManager.GetString("Text_Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 名称 的本地化字符串。
        /// </summary>
        internal static string Text_Name {
            get {
                return ResourceManager.GetString("Text_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 新增 的本地化字符串。
        /// </summary>
        internal static string Text_New {
            get {
                return ResourceManager.GetString("Text_New", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 什么都没有…… 的本地化字符串。
        /// </summary>
        internal static string Text_Nothing {
            get {
                return ResourceManager.GetString("Text_Nothing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 搜索 的本地化字符串。
        /// </summary>
        internal static string Text_Search {
            get {
                return ResourceManager.GetString("Text_Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 显示方式 的本地化字符串。
        /// </summary>
        internal static string Text_ShowStyle {
            get {
                return ResourceManager.GetString("Text_ShowStyle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 查看 的本地化字符串。
        /// </summary>
        internal static string Text_View {
            get {
                return ResourceManager.GetString("Text_View", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 主题 的本地化字符串。
        /// </summary>
        internal static string Theme {
            get {
                return ResourceManager.GetString("Theme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 浅色,深色 的本地化字符串。
        /// </summary>
        internal static string ThemeSelect_Items {
            get {
                return ResourceManager.GetString("ThemeSelect.Items", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 账号不正确 的本地化字符串。
        /// </summary>
        internal static string Valid_Account {
            get {
                return ResourceManager.GetString("Valid_Account", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 账号不能为空 的本地化字符串。
        /// </summary>
        internal static string Valid_AccountRequired {
            get {
                return ResourceManager.GetString("Valid_AccountRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 密码不能为空 的本地化字符串。
        /// </summary>
        internal static string Valid_PasswordRequired {
            get {
                return ResourceManager.GetString("Valid_PasswordRequired", resourceCulture);
            }
        }
    }
}
